
  name: Blob Storage Website CI

  on:
    push:
      tags:
        - v[0-9]+.[0-9]+.[0-9]+
    workflow_dispatch:

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '>=18'
      - name: Install dependencies
        run: yarn install
      - name: Build project
        run: yarn generate
      - uses: azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      # Delete existing content in $web container
      - name: Delete existing content in $web container
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob delete-batch --account-name ${{ vars.ACCOUNT_NAME }} --auth-mode key -s '$web'
            
      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
              az storage blob upload-batch --account-name ${{ vars.ACCOUNT_NAME }} --auth-mode key -d '$web' -s ./dist

    # Azure logout
      - name: logout
        run: |
              az logout
        if: always()
  